{% set name = "llmlingua" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llmlingua-{{ version }}.tar.gz
  sha256: 1a0caedd8d5a65512a85dadb6bfda6f5b3c4b45e5cb9e7b1c6009573f9058572

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - transformers >=4.26.0
    - accelerate
    - pytorch
    - tiktoken
    - nltk
    - numpy

test:
  imports:
    - llmlingua
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/LLMLingua
  summary: "To speed up LLMs' inference and enhance LLM's perceive of key information, compress the prompt and KV-Cache, which achieves up to 20x compression with minimal performance loss."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
